import { PostgrestClient } from '@supabase/postgrest-js'

const REST_URL = 'http://localhost:3000'

const finexPostgRESTClient = new PostgrestClient(REST_URL, {
  // TODO: JWT
  headers: {
    "Authorization": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTc1NTU3MTQsInN1YiI6IjA1OWZiN2UyLTM4OWEtNGI1Yy04MGIxLTYzODUyZDkyOGNkNiIsImVtYWlsIjoiIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJBc3ltbWV0cmljS2V5IiwicHJvdmlkZXJzIjpbIkFzeW1tZXRyaWNLZXkiXX0sInVzZXJfbWV0YWRhdGEiOnt9LCJyb2xlIjoic3VwZXJhZG1pbiIsImFzeW1tZXRyaWNfa2V5IjoiMHhkODVGODgzYTZCMmUxNUJEM2UxZDZDOTM5ODY2Q0E5NWY4MDJCMzk2IiwiYXN5bW1ldHJpY19rZXlfYWxnb3JpdGhtIjoiRVRIIn0.YWsmVYFtBgtDrgqCgcWDJTDyQHhyWvNT23COqSPavmUrK-cI8a2vWK5q_7olK53a3jtck8KcdGG0SkcqapnqnHvCAUYQ4PSLulR5P3sHmh5AgqZKVsppDMKyW5GF3xyLwtos1Kj_JcXKwBIyrwCFTadCMskUHXhpGfTC47rliL_5JQ8d7gPMQcDrjKfzNmyKmLlCrn6J7gesrnDFaVvzXmxgBUiJFk5GGHsq7jLoTf47wCgZbqpGOKUf9-Wc_sumFEb26bAX8KZOK3szGJXlXTJwPVwc40rrLxY4Hof2CgxFRIPJCvaFXSJCS4CimzK8chbpWyNj5paU-uVi4mzcCg"
  },
  schema: 'finex'
});

export { finexPostgRESTClient }
