---
kind: pipeline
type: docker
name: Studio

concurrency:
  limit: 2

steps:
  - name: Save Git SHA
    image: alpine:3
    pull: if-not-exists
    commands:
      - echo '${DRONE_SOURCE_BRANCH//\//-},${DRONE_COMMIT:0:7}' > .tags

  - name: Docker build SHA
    image: plugins/docker:20
    pull: if-not-exists
    settings:
      dockerfile: studio/Dockerfile
      target: production
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
      repo: quay.io/openware/studio
      registry: quay.io
      context: studio
      cache_from:
        - "quay.io/openware/studio:master"
        - 'quay.io/openware/studio:${DRONE_SOURCE_BRANCH//\//-}'

trigger:
  event:
    - push
  branch:
    - master
    - feature/*
    - feat/*
    - fix/*
